#!/usr/bin/env bash
# Script to display information about subdomains

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
	subdomains=("www" "lb-01" "web-01" "web-02")
else
	subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
	record=$(dig +short "$sub.$domain" | head -n1)
	record_type=$(dig +short "$sub.$domain" | tail -n1)
	echo "The subdomain $sub is a $record_type record and points to $record"
done
