#!/usr/bin/env bash
# This script transfers a file from our client to a server:
# 	accepting 4 parameters:
# 	display a message if less than 3 param are entered
# 	scp must transfer file to user home dir
# 	Strict host key checking must be disabled when using scp

if [ $# -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	#assigns parameters to varibles
	file_path="$1"
	server_ip="$2"
	username="$3"
	ssh_key="$4"

	# Transfer file using scp
	scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~ 
fi
