#!/usr/bin/env bash
# redirects to the said path permanently

sudo apt-get update -y

sudo apt-get install -y nginx

# content to be loaded by root request
echo "Hello World!" |sudo tee /var/www/html/index.html > /dev/null

sudo tee /etc/nginx/sites-available/default >/dev/null <<EOF
server {
        listen 80;
        listen [::]:80 default_server;
        server_name _;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
        location @404 {
                 return 404 "Ceci n'est pas une page.";
        }


        root /var/www/html;
        error_page 404 = @404;
}
EOF

sudo service nginx restart
