#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure HAProxy can be managed via an init script

# Update package repository
sudo apt-get update

# Install HAProxy
export DEBIAN_FRONTEND=noninteractive
sudo apt-get install -y haproxy

# Create directory if it doesn't exist
sudo mkdir -p /etc/haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

# Define HAProxy configuration
haproxy_config="
global
	log /dev/log    local0
	log /dev/log    local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log     global
	mode    http
	option  httplog
	option  dontlognull
	timeout connect 5000
	timeout client  50000
	timeout server  50000

frontend prudigy_frontend
	bind *:80
	mode http
	default_backend prudigy_backend

backend prudigy_backend
	balance roundrobin
	server 494470-web-01 100.25.156.254:80 check
	server 494470-web-02 54.85.20.151:80 check
"

# Write HAProxy configuration to file
echo "$haproxy_config" | sudo tee /etc/haproxy/haproxy.cfg

# Enable HAProxy management via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo systemctl restart haproxy
