#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

# create PID file
echo "$$" > /var/run/myscript.pid

# Display to infinity and beyond inde...
while true; do
	echo "To infinity and beyond"
	sleep 2
done

# Function to handle SIGTERM signal
terminate() {
	echo "I hate the kill command"
	cleanup_and_exit
}

# Function to handle SIGINT signal
interrupt() {
	echo "Y U no love me?!"
}

# Function to handle SIGQUIT signal
quit() {
	echo "Received SIGQUIT. Cleaning up and exiting."
	cleanup_and_exit
}

# Function to perform cleanup and exit
cleanup_and_exit() {
	rm -f /var/run/myscript.pid
	echo "Cleanup complete. Exiting."
	exit 0
}

# Register signal handlers
trap 'terminate' SIGTERM
trap 'interrupt' SIGINT
trap 'quit' SIGQUIT
