#!/usr/bin/env bash 
# stops 4-to_infinity_and_beyond process.using kill(sigkill)

#get program pid
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

#terminate the infinite process
if [ -n "$id" ]; then
	kill -15 "$id"
fi
