#!/usr/bin/env bash
#displays the content of the file /etc/passwd.only displays useername, id and home dir

while IFS=':' read -r username _ uid _ _ home _; do
	echo "$username:$uid:$home"
done < /etc/passwd
