#!/bin/bash
#displays the content of the file /etc/passwd.only displays useername, id and home dir

while IFS=':' read -r username x uid gid info home shell; do
	echo "$username:$uid:$home"
done < /etc/passwd
