#!/usr/bin/env bash
# This script tells the story of /etc/passwd

# Read the file /etc/passwd line by line
while IFS=: read -r username password uid gid info home shell; do
      	# Extract information and format it into a story
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
