#!/usr/bin/env bash
# display information about users from /etc/passwd

temp_file=$(mktemp)
while IFS=':' read -r username _ uid gid info home shell; do
	passcode=$(grep "^$username:" /etc/shadow | cut -d: -f2)
	id_info="$info"

	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $id_info"
done < /etc/passwd > "$temp_file"

# Read from the temporary file
cat "$temp_file"

# Remove the temporary file
rm "$temp_file"
