#!/usr/bin/env bash
# Displays "Best School" 10 times but on the 9th iteration it adds hi on a new line

counter=0

while [ $counter -lt 10 ]; do
	if [ $counter -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done
