#!/usr/bin/env bash
# loops from 1 -10 and displays bad luck on 4th, good luck on 8th and Best school on all other iterations

counter=0

while [ $counter -lt 10 ]; do
	if [ $counter -eq 3 ]; then
		echo "bad luck"
	elif [ $counter -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
