#!/usr/bin/env bash
# This script configures the Ubuntu server with specific IP resolutions.

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8           facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
